### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by coreybruce** [steamlink/steamlink#2]
Manjaro ARM Arm64 Raspberry pi 4 

`(sl) [corey@manjaro-pi steamlink]$ steamlink
Traceback (most recent call last):
  File "/home/corey/stuff/steamlink/sl/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/corey/stuff/steamlink/sl/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/corey/stuff/steamlink/sl/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Jinja2 2.10 (/home/corey/stuff/steamlink/sl/lib/python3.8/site-packages/Jinja2-2.10-py3.8.egg), Requirement.parse('jinja2>=2.10.1'), {'aiohttp-jinja2'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/corey/stuff/steamlink/sl/bin/steamlink", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/corey/stuff/steamlink/sl/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/home/corey/stuff/steamlink/sl/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/corey/stuff/steamlink/sl/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/corey/stuff/steamlink/sl/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/corey/stuff/steamlink/sl/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/corey/stuff/steamlink/sl/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Jinja2 2.10 (/home/corey/stuff/steamlink/sl/lib/python3.8/site-packages/Jinja2-2.10-py3.8.egg), Requirement.parse('jinja2>=2.10.1'), {'aiohttp-jinja2'})`

**Comment by buvanenko** [comment]
Same problem on Debian 10
